#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/rpi_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
cd $dir
sh=../../raspberry-pi.sh
test -x $sh || die "Not executable [$sh]"
eval $($sh env)
eval $($sh versions --brief)
bb=$RASPBERRYPI_WORKSPACE/$ver_busybox/busybox
test -x $bb || die "Not executable [$bb]"
d=$musldir/aarch64/aarch64-linux-musl/lib
test -d $d || die "Not a directory [$d]"

mkdir -p $tmp/bin $tmp/lib
cp -r * $tmp
cp $bb $tmp/bin
cp -L $d/lib*.so.[0-9] $tmp/lib
cp $d/libc.so $tmp/lib/ld-musl-aarch64.so.1
cd $tmp

tar --exclude='tar' --exclude='README.md' -cf "$1" *
rm -rf $tmp
